server:
  port: 8072

# dubbo
dubbo:
  application:
    name: zqls-passport-web
  registry:
    address: zookeeper://39.106.154.120:2181
  protocol:
    name: dubbo

# log
logging:
  level:
    com:
      duanxin:
        zqls:
          passport: debug